standard:
  9:
    position: 
      cartesian:
        x:         3.265
        y:        -1.065
        z:         0.410
  10:
    position: 
      cartesian:
        x:         0.995
        y:        -2.268
        z:         0.410
  11:
    position: 
      cartesian:
        x:        -1.269
        y:        -2.318
        z:         0.410
  12:
    position: 
      cartesian:
        x:        -3.124
        y:        -1.250
        z:         0.410
  13:
    position: 
      cartesian:
        x:        -3.249
        y:         1.433
        z:         0.410
  14:
    position: 
      cartesian:
        x:        -1.553
        y:         2.814
        z:         0.410
  15:
    position: 
      cartesian:
        x:         1.254
        y:         2.946
        z:         0.410
  16:
    position: 
      cartesian:
        x:         3.145
        y:         1.474
        z:         0.410