FeatureTracker:
  features:
    1: 
      name: "Centroid"
      param: null
    2: 
      name: "Rolloff"
      param: null

FeatureProcessor: null

SpeakerManager: 
  array: "EN325_21.yaml"
  selected: "mid_circle"
  mid_circle:
    unmasked: [9, 10, 11, 12, 13, 14, 15, 16]
    subindex: [12, 13, 14, 15, 16, 9, 10, 11]
    topology: 
      9:  [12]
      10: [13]
      11: [14]
      12: [15]
      13: [16]
      14: [9]
      15: [10]
      16: [11]
  above_head:
    unmasked: [17, 18, 19, 20, 21]
    subindex: []
    topology:
      17: [21]
      18: [21]
      19: [21]
      20: [21]
      21: [17, 18, 19, 20]

EnvelopeGenerator:
  mode: "trajectory"

EnvelopeCombinator: 
  n_source:  2
  n_channel: 8
  mode: "square_root"

AudioDisperser: null
