input:
  1: 
    name: "mono"
features:
  1: 
    name: "Centroid"
    mode: "normalized"
  2: 
    name: "RMSAmplitude"
    mode: "normalized"
  3: 
    name: "ZeroCrossingRate"
    mode: "normalized"
trajectory:
  mode: "bypass"
mapper:
  mode: "triggering"
router:
  mode: "copy"

