speakers:
  1:
    x: 3.0
    y: 1.7
    z: 0.0
    directness: 1.0
    connected: [1, 7]
  2:
    x: 1.7
    y: 1.7
    z: 1.7
    directness: 1.0
    connected: [0, 2]
  3:
    x: 0.0
    y: 1.7
    z: -3.0
    directness: 1.0
    connected: [1, 3]
  4:
    x: 0.0
    y: 1.7
    z: 1.7
    directness: 1.0
    connected: [2, 4]
  5:
    x: 0.0
    y: 1.7
    z: 1.7
    directness: 1.0
    connected: [3, 5]
  6:
    x: 0.0
    y: 1.7
    z: 1.7
    directness: 1.0
    connected: [4, 6]
  7:
    x: 0.0
    y: 1.7
    z: 1.7
    directness: 1.0
    connected: [5, 7]
  8:
    x: 0.0
    y: 1.7
    z: 1.7
    directness: 1.0
    connected: [6, 0]
