speakers:
  0:
    x: 0.0
    y: 0.5
    z: 0.0
    directness: 1.0
    connected: [1]
  1:
    x: 0.0
    y: 1.0
    z: 0.0
    directness: 1.0
    connected: [2]
  2:
    x: 0.0
    y: 1.5
    z: 0.0
    directness: 1.0
    connected: [3]
  3:
    x: 0.0
    y: 2.0
    z: 0.0
    directness: 1.0
    connected: [4]
  4:
    x: 0.0
    y: 2.5
    z: 0.0
    directness: 1.0
    connected: [5]
  5:
    x: 0.0
    y: 3.0
    z: 0.0
    directness: 1.0
    connected: [6]
  6:
    x: 0.0
    y: 3.5
    z: 0.0
    directness: 1.0
    connected: [7]
  7:
    x: 0.0
    y: 4.0
    z: 0.0
    directness: 1.0
    connected: [0,1,2,3,4,5,6]
