speakers:
  1:
    x: 3.0
    y: 1.7
    z: 0.0
    directness: 1.0
    connected: [8, 1]
  2:
    x: 1.7
    y: 1.7
    z: 1.7
    directness: 1.0
    connected: [1, 3]
  3:
    x: 0.0
    y: 1.7
    z: -3.0
    directness: 1.0
    connected: [2, 4]
  4:
    x: 0.0
    y: 1.7
    z: 1.7
    directness: 1.0
    connected: [3, 5]
  5:
    x: 0.0
    y: 1.7
    z: 1.7
    directness: 1.0
    connected: [4, 6]
  6:
    x: 0.0
    y: 1.7
    z: 1.7
    directness: 1.0
    connected: [5, 7]
  7:
    x: 0.0
    y: 1.7
    z: 1.7
    directness: 1.0
    connected: [6, 8]
  8:
    x: 0.0
    y: 1.7
    z: 1.7
    directness: 1.0
    connected: [7, 1]
  9:
    x: 0.0
    y: 1.7
    z: 1.7
    directness: 1.0
    connected: [7, 1]
  10:
    x: 0.0
    y: 1.7
    z: 1.7
    directness: 1.0
    connected: [7, 1]
  11:
    x: 0.0
    y: 1.7
    z: 1.7
    directness: 1.0
    connected: [7, 1]
  12:
    x: 0.0
    y: 1.7
    z: 1.7
    directness: 1.0
    connected: [7, 1]
  13:
    x: 0.0
    y: 1.7
    z: 1.7
    directness: 1.0
    connected: [7, 1]
  14:
    x: 0.0
    y: 1.7
    z: 1.7
    directness: 1.0
    connected: [7, 1]
  15:
    x: 0.0
    y: 1.7
    z: 1.7
    directness: 1.0
    connected: [7, 1]
  16:
    x: 0.0
    y: 1.7
    z: 1.7
    directness: 1.0
    connected: [7, 1]
  17:
    x: 0.0
    y: 1.7
    z: 1.7
    directness: 1.0
    connected: [7, 1]
  18:
    x: 0.0
    y: 1.7
    z: 1.7
    directness: 1.0
    connected: [7, 1]
  19:
    x: 0.0
    y: 1.7
    z: 1.7
    directness: 1.0
    connected: [7, 1]
  20:
    x: 0.0
    y: 1.7
    z: 1.7
    directness: 1.0
    connected: [7, 1]
  21:
    x: 0.0
    y: 1.7
    z: 1.7
    directness: 1.0
    connected: [7, 1]
